### PR TITLE
feat: Implemented build checks using Github Actions for Go-SDK

### PR DESCRIPTION
**Pull request by khanjasir90**
Signed-off-by: khanjasir90 <khanmohdjasir@gmail.com>
Implemented build checks using github actions for go-sdk

### CODE REVIEW

**Comment by khanjasir90** [comment]
@slayerjain after rebase build works properly though tests are failing due to some connection error could u pls look into that

**Comment by khanjasir90** [comment]
@slayerjain ig we should remove the test job for the time being! since the pr is focused on build. what are ur thoughts on this.

**Comment by slayerjain** [comment]
@khanjasir90 We are planning to add tests in coming future, so it would be good to keep it. Give me sometime. I’ll look into this error

**Comment by khanjasir90** [comment]
Got it!

**Comment by slayerjain** [comment]
@khanjasir90 please rebase with the `main` branch. `go test -v ./...` should now work :)

**Comment by khanjasir90** [comment]
@slayerjain will do it asap!

**Comment by khanjasir90** [comment]
@slayerjain it works 👍! go test now works! now we can add more strict i.e min 2 reviews required before merge !

**Comment by slayerjain** [comment]
@khanjasir90 yes, this look perfect. Thanks!

**Pull request merged**
